Add a plugin mechanism to tukit
openSUSE/transactional-update pull request #122
Opened 2024-05-22 22:49 UTC by aplanas

2024-05-22 22:50 UTC, aplanas commented on lib/Transaction.hpp
> +    std::filesystem::path getBindDir();
Not happy about this, but the alternatives that I thought were worse. Any suggestion?

2024-05-23 12:47 UTC, aplanas commented on lib/Transaction.hpp
> +    std::filesystem::path getBindDir();
Resolved in the next commit

2024-05-23 12:47 UTC, aplanas commented
Ready for reviews!

cc @Vogtinator

2024-06-03 15:26 UTC, aplanas commented
@laenion @Vogtinator ping? : )

2024-06-25 15:35 UTC, laenion requested changes
In general I like the approach - see the nits, but the place to call the plugins will have to be changed in any case.

(I'm still not sure whether it's a good idea to have the BindDir as part of the API, but I'll not complain for now ;-))

2024-06-25 15:35 UTC, laenion commented on doc/tukit-plugins.md
> +itself, depending if makes sense in the context of this action.  The
depending if ***it*** makes sense

2024-06-25 15:35 UTC, laenion commented on doc/tukit-plugins.md
> +next table summarize the action, the stage and different parameters
summarize***s***

2024-06-25 15:35 UTC, laenion commented on doc/tukit-plugins.md
> +	# "/.snapshots/${snapshot_id}/snapshot
Different spacings.

2024-06-25 15:35 UTC, laenion commented on lib/Plugins.cpp
> +            tulog.info("Regiter plugin ", path);
Typo, but I would also say "Found plugin " instead.

2024-06-25 15:35 UTC, laenion commented on lib/Plugins.cpp
> +            tulog.info("plugin ", p, " output: ", output);
I'm not sure we want to print this text every time, even when when the plugin didn't even print something itself. On the other hand I do indeed see the necessity that some plugins have to print important information. I'd suggest to only print this line if the output is not empty.

A second point: When starting tukit with `--verbose`, then the output of the plugin will be printed by `Util::exec` itself already, but I guess it's acceptable when the output it printed twice then.

And last: Please use a capital 'P' in "plugin", or - which I'd prefer - "Output of plugin xxx: "

2024-06-25 15:35 UTC, laenion commented on lib/Plugins.cpp
> +            tulog.error("ERROR: plugin ", p, " fails with ", e.what());
Capital "P" in "plugin
"fails" -> "failed"

2024-06-25 15:35 UTC, laenion commented on tukit/tukit.cpp
> +#include "Plugins.hpp"
I assume the plugins are also supposed to run when calling tukit via D-Bus or the C and C++ APIs. Due to that all of the calls from below have to be moved to the functions they are wrapping.

2024-06-25 15:35 UTC, laenion commented on sbin/Makefile.am
> +	-e 's,[@]libdir[@],$(libdir),g' \
This seems to be unused?

2024-06-25 15:44 UTC, aplanas commented on doc/tukit-plugins.md
> +itself, depending if makes sense in the context of this action.  The
done

2024-06-25 15:45 UTC, aplanas commented on doc/tukit-plugins.md
> +next table summarize the action, the stage and different parameters
done

2024-06-25 15:46 UTC, aplanas commented on doc/tukit-plugins.md
> +	# "/.snapshots/${snapshot_id}/snapshot
done

2024-06-25 15:46 UTC, aplanas commented on lib/Plugins.cpp
> +            tulog.info("Regiter plugin ", path);
yes, done

2024-06-25 15:50 UTC, aplanas commented on lib/Plugins.cpp
> +            tulog.info("plugin ", p, " output: ", output);
done

2024-06-25 15:50 UTC, aplanas commented on lib/Plugins.cpp
> +            tulog.error("ERROR: plugin ", p, " fails with ", e.what());
done

2024-06-25 15:56 UTC, aplanas commented on sbin/Makefile.am
> +	-e 's,[@]libdir[@],$(libdir),g' \
I think that is used in transactional-update.in, in variable STATUS_FILE, BASE_MANIFEST_FILE and SYSTEM_MANIFEST_FILE?

2024-06-25 17:00 UTC, aplanas commented on tukit/tukit.cpp
> +#include "Plugins.hpp"
That is a good point, but they cannot be moved into the commands?

There is not a perfect mapping, for example, the abort() cannot be mapped intro resume(), as it is used also in close()

2024-06-25 17:03 UTC, aplanas commented on tukit/tukit.cpp
> +#include "Plugins.hpp"
I guess that the best option is to also add the plugins into the bindings and dbus entry points?, or do you see a way to map then?

2024-06-25 17:09 UTC, aplanas commented on tukit/tukit.cpp
> +#include "Plugins.hpp"
ah, cannot be added into the binding, a binding should be created instead ...

2024-06-26 15:53 UTC, aplanas commented on tukit/tukit.cpp
> +#include "Plugins.hpp"
Should be done, but I changed the semantic of some of the stages

2024-06-26 15:54 UTC, aplanas commented
@laenion should be ready for another pass

2024-07-01 15:11 UTC, laenion commented on doc/tukit-plugins.md
> +the user API level.  This means that some verbsq like `tukit exeture
2x "from" -> "of", I'd also suggest "based on" instead of "linked to"
"verbsq" -> "verbs"
"exeture" -> "execute"

2024-07-01 15:11 UTC, laenion commented on doc/tukit-plugins.md
> +
Just as a comment: The option to call plugins for `Reboot::Reboot` and `SnapshotManager::rollbackTo` has gone now. The former would be trivial to implement, the later would be a bit more work because it's just a virtual method currently. Let's see whether we need it, but I guess `reboot` makes sense in any case.

2024-07-01 15:11 UTC, laenion commented on sbin/Makefile.am
> +	-e 's,[@]libdir[@],$(libdir),g' \
Indeed. That may have been one reason why the `status` command hasn't worked as intended...

2024-07-01 15:11 UTC, laenion commented on doc/tukit-plugins.md
> +|          | -post | path, snapshot\_id, action params |       |
I'm wondering whether it wouldn't make sense to also have one "common" action target such as `runCommand` to run a plugin independent of the specific entry point...
Unfortunately naming is not ideal :/
Opinions?

2024-07-01 15:30 UTC, aplanas commented on doc/tukit-plugins.md
> +the user API level.  This means that some verbsq like `tukit exeture
yes, done

2024-07-01 15:31 UTC, aplanas commented on doc/tukit-plugins.md
> +|          | -post | path, snapshot\_id, action params |       |
For me is more important the consistency. If we are mapping the libtukit, we need to reflect it in the plugins.

2024-07-01 15:33 UTC, aplanas commented on doc/tukit-plugins.md
> +|          | -post | path, snapshot\_id, action params |       |
uhmm also there will be two entry points for the same action, that will be very confusing ...

2024-07-01 15:37 UTC, aplanas commented on doc/tukit-plugins.md
> +
Added the `reboot` one.

2024-07-01 20:52 UTC, laenion commented
Thanks a lot for all your work, everything is looking good now! Just one last thing: The last two commits are messed up, "[tukit: move getBindDir as protected](https://github.com/openSUSE/transactional-update/pull/122/commits/857c8969fec2811545d07262b55ff4a54b9995a0)" now contains all the changes that should have gone into "[tukit: add plugin mechanism](https://github.com/openSUSE/transactional-update/pull/122/commits/c374ee94d6684efa5adeda71d55e94fe698671a3)"

2024-07-01 21:02 UTC, aplanas commented
> The last two commits are messed up

Ah indeed. I squashed both.

2024-07-02 11:38 UTC, merged

2024-07-02 11:39 UTC, laenion reviewed
Looking good now, thanks a lot for your work!

2024-07-02 11:44 UTC, aplanas commented
Thanks for your reviews @laenion. That helped a lot.