Adding support for specifying migration arguments
openSUSE/transactional-update pull request #127
Opened 2024-07-18 15:45 UTC by rdoxenham

This PR adds support for providing arguments to the `transactional-upgrade migration` command, which is useful if you want to override certain functionality, e.g. if you're wanting to call for a specific product to be migrated to in fully-automated use-cases. The code also catches the usage of `--root` where we would want to prevent this from being overridden from the default, which is populated by `transactional-update`.

2024-07-18 22:30 UTC, laenion requested changes

2024-07-18 22:30 UTC, laenion commented on sbin/transactional-update.in
> +		MIGRATION_ARGS="$*";
This variable should be an array like `ZYPPER_ARG_PKGS`, otherwise it won't be possible to use arguments containing characters such as spaces.

Also see the comment for the actual zypper invocation below.

2024-07-18 22:30 UTC, laenion commented on sbin/transactional-update.in
> +	    tukit ${TUKIT_OPTS} callext "${SNAPSHOT_ID}" zypper ${ZYPPER_ARG} --root {} ${MIGRATION_ARGS} ${ZYPPER_NONINTERACTIVE} "${ZYPPER_ARG_PKGS[@]}" |& tee -a ${LOGFILE} 1>&${origstdout}
`${MIGRATION_ARGS}` and `${ZYPPER_ARG_PKGS}` serve the same purpose: they will add additional parameters to the zypper command, though `${ZYPPER_ARG_PKGS}` was unused in this context so far.

Together with the comment from above (conversion to an array) I'd suggest to just reuse `${ZYPPER_ARG_PKGS}` here instead of introducing another variable, but rename `${ZYPPER_ARG_PKGS}` to something more reasonable (because it was also possible to use `${ZYPPER_ARG_PKGS}` for command options in the context of installing packages anyway).
(I currently can't think of any really good name though. `${ZYPPER_ARG_ARGS}` would be the most logical one given the current names... Renaming `${ZYPPER_ARG}` to something like `${ZYPPER_COMMAND}` is definitely out of scope for this ticket :-))

2024-07-19 09:26 UTC, rdoxenham commented on sbin/transactional-update.in
> +	    tukit ${TUKIT_OPTS} callext "${SNAPSHOT_ID}" zypper ${ZYPPER_ARG} --root {} ${MIGRATION_ARGS} ${ZYPPER_NONINTERACTIVE} "${ZYPPER_ARG_PKGS[@]}" |& tee -a ${LOGFILE} 1>&${origstdout}
Thanks @laenion - I've refactored this to accommodate. I've gone with `${ZYPPER_ARG_ADDL}` as an "additional" set of flags that would be acceptable for a wide variety of additional items, e.g. specifying packages to install via `zypper in` or specifying the product to install via `zypper migration` as per this original PR suggestion. Let me know if you're happy with this approach. Thanks!

2024-07-19 09:34 UTC, aplanas commented on sbin/transactional-update.in
> +ZYPPER_ARG_ADDL=()
May I suggest `ZYPPER_ARG_EXT` or `ZYPPER_ARG_EXTRA`. I saw it as a common idiom.

2024-07-19 09:34 UTC, aplanas commented on sbin/transactional-update.in
> +			    log_error "ERROR: You can't set '--root' when running 'zypper migration' in transactional-update."
I am wondering if this is something specific to migration or t-u. I suspect that `--root` is of no use in any case, so maybe move it into the L920 loop?

2024-07-19 09:46 UTC, rdoxenham commented on sbin/transactional-update.in
> +			    log_error "ERROR: You can't set '--root' when running 'zypper migration' in transactional-update."
@aplanas thanks for the review... I can move it to the loop in L920, but that's specifically for the `ptf|pkg|package` in the case switch; I'd need to replicate it for `migration`.

2024-07-19 09:55 UTC, aplanas commented on sbin/transactional-update.in
> +			    log_error "ERROR: You can't set '--root' when running 'zypper migration' in transactional-update."
ah right, one option is to refactor it a bit:

```bash
parse_zypper_args_extra() {
  while [ 1 ]; do
    if [ $# -eq 0 ]; then
      break;
    else
      if [ "$1" == "--root" ]; then
        log_error "ERROR: You can't set '--root' in transactional-update."
        exit 1
      fi
      ZYPPER_ARG_ADDL+=("$1");
      shift
    fi
  done
}
```

Later is both switch arms you can place the call

2024-07-19 11:40 UTC, rdoxenham commented on sbin/transactional-update.in
> +			    log_error "ERROR: You can't set '--root' when running 'zypper migration' in transactional-update."
Thanks for the input again, @aplanas. I've gone with your suggestion and putting this into its own function, but the original design handles all of the command line arguments, allowing `transactional-update` commands to be strung together, e.g. `transactional-update grub.cfg pkg in <whatever>`. Given that we're parsing the arguments in a separate function, it's not `shift`'ing them as expected, which means I have to `break` out of the while loop if any `transactional-update` command gets executed where we need to parse these extra arguments. I've tested this, and I can't actually see why this would make much of a difference, you would just always need to make sure that your `pkg in` commands were last, which I think they need to be anyway.

2024-07-19 11:57 UTC, aplanas commented on sbin/transactional-update.in
> +			    log_error "ERROR: You can't set '--root' when running 'zypper migration' in transactional-update."
Thanks a lot for retesting it. I think that the last while will consume all the parameters anyway.

For what it is worth LGTM

2024-07-23 15:32 UTC, laenion commented
Perfect, thanks a lot.

The only remaining place that needs to be adopted is the documentation in https://github.com/openSUSE/transactional-update/blob/master/man/transactional-update.8.xml#L437 to mention the arguments, probably similar to the `pkg` or `register` description.

2024-07-25 14:08 UTC, rdoxenham commented
Thanks @laenion - I've added the changes to the man pages to reference the fact that this command now supports arguments.

2024-07-31 13:29 UTC, merged

2024-07-31 13:30 UTC, laenion commented
Thanks a lot for you work and all the subsequent fixes - merged!