Support sdbootutil in transactional-update
openSUSE/transactional-update pull request #130
Opened 2024-08-21 14:17 UTC by aplanas

If sdbootutil is used, some actions like initrd generation or bootloader installation should happen outside the transaction.

Some other actions, like the rewrite of the GRUB configuration file are noop.

Also the call to mkdumprd should happen outside the transaction, but due to some pbl issues this is a noop for now (with a warning message)

2024-08-21 14:32 UTC, laenion requested changes

2024-08-21 14:32 UTC, laenion commented on sbin/transactional-update.in
> +is_bls() {
Danilo introduced `HAS_BLS_SUPPORT` already, using the presence of of _/etc/kernel/cmdline_ as an indicator. I guess only one of these should be used?

2024-08-21 14:32 UTC, laenion commented on sbin/transactional-update.in
> +
These variables will also be changed and set to `1` again from the lines that follow (e.g. from the various `SETUP_*` blocks).

The code will have to be moved into the corresponding blocks processing these variables.

2024-08-21 15:02 UTC, aplanas commented on sbin/transactional-update.in
> +is_bls() {
Good point.  I used `is_bls` all around. Is the more canonical check

2024-08-21 15:03 UTC, aplanas commented on sbin/transactional-update.in
> +
Instead of moving the code (as this will start the transaction that we do not want), I make sure that the variables are not re-set when `is_bls` is true

2024-08-22 11:08 UTC, aplanas commented
Ready for another pass

2024-08-22 11:55 UTC, merged

2024-08-22 12:00 UTC, laenion commented
Looks good now - merged!

2024-08-22 12:00 UTC, laenion reviewed
Looks good now!