Implement core functionality in C++: transkit / libt-u
openSUSE/transactional-update pull request #31
Opened 2020-07-12 19:05 UTC by laenion

This pull request introduces the `libt-u.so` library with the goal to replace the core functionality of the existing `transactional-update` with a modern C++ library. The library is supposed to be used by package managers such as zypper or dnf in the future.

This pull request, however, only introduces an application called `transkit`, which will allow access to the API from the command line. The `transactional-update` command has been changed to use the application.

2020-07-12 19:24 UTC, laenion commented
@Vogtinator: This is the initial version for review (and to check whether I'm on the right track).
Currently has logging level set to debug and does not set the new snapshot as the default snapshot - both of these are left for debugging and will be changed before merging.

2020-07-13 13:51 UTC, Vogtinator requested changes
`+2,033 −596` :-(
With the old script, it was much easier to get a grasp of what's going on. That's unfortunately not the case anymore.

I didn't complete the high level review yet, so mostly low-level comments so far.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Configuration.h
> +#include <libeconf.h>
Only a pointer is used here, so just forward declaring `struct econf_file;` saves including all of that every time `Configuration` is used.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Configuration.cpp
> +/*
Can we standardize on SPDX license headers? https://spdx.dev/ids/#how

2020-07-13 13:51 UTC, Vogtinator commented on lib/Configuration.cpp
> +    for(auto &e : defaults) {
```
    for(auto &[key, value] : defaults) {
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Configuration.h
> +inline Configuration config{};
This means the constructor is run as part of static initialization, which is not great as it does IO and can throw.
There's also no reason to have more than one `Configuration` object globally, so I suggest this:

```
class Configuration {
public:
    std::string get(const std::string &key);
    static Configuration &instance();
private:
    Configuration();
    ~Configuration();
    econf_file *key_file;
};

Configuration &Configuration::instance()
{
    static Configuration c;
    return c;
}
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Configuration.h
> +    std::string get(const std::string &key);
If this is copied, it'll blow up with a UAF, so:
```
Configuration(const Configuration&) = delete;
void operator=(const Configuration&) = delete;
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Configuration.h
> +#ifndef CONFIGURATION_H_
`#pragma once`?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Exceptions.h
> +    int getReturnCode() {
Just make it a `public const int` member?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Exceptions.h
> +    ExecutionException(std::string why, int status) : reason{why}, returncode{status} {
Copies `why` twice. Either `const std::string &why ... reason{why}` or `std::string why ... reason{std::move(why)}`.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Exceptions.h
> +    ExecutionException(std::string why, int status) : reason{why}, returncode{status} {
You can have arguments and members with the same name

2020-07-13 13:51 UTC, Vogtinator commented on lib/Exceptions.h
> +    const char* what() const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override {
Why make this libstdc++ specific?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Log.h
> +        time_t now = time(0);
Either `std::time` and `std::localtime` or `::time` and `::localtime`

2020-07-13 13:51 UTC, Vogtinator commented on lib/Log.h
> +        if (int(level) >= int(TULogLevel::ERROR))
`enum class` has the advantage that it doesn't implicitly convert to int, but here every single use of it is as int...

You could just implement `operator >=` here.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Log.h
> +inline TULog tulog{};
Same comment as for `Configuration`.

Though in this case the class doesn't have state, so all there is is a global log level. Just make that and all other methods `static`?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.h
> +#ifndef LIBMOUNTWRAPPER_H
Wrong name

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.h
> +class Mount
The class and its methods need documentation. It's not obvious what it represents and does

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    if ((rc = mnt_table_parse_mtab(umount_table, NULL)) != 0)
Can be avoided if this is uninitialized or a moved-from instance.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    : mnt_cxt{NULL}, mnt_table{mnt_new_table()}, mnt_fs{NULL},
`s/NULL/nullptr/g` everywhere please

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    : mnt_cxt{NULL}, mnt_table{NULL}, mnt_fs{NULL}
Just initialize them in the member declaration

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    struct libmnt_fs *umount_fs;
This isn't C90 - you can move the declarations to where they're actually used

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    int rc;
Not really needed

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +        if ((rc = mnt_table_parse_fstab(mnt_table, NULL)) != 0)
C++17 FTW:

```
        if (int rc = mnt_table_parse_fstab(mnt_table, NULL); rc != 0)
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    tabsource = source;
This has non-obvious behavior as `mnt_fs` is "cached" by `getTabEntry`. So calling `setTabSource` after `getTabEntry()` was called is a noop and results in an inconsistency.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    return mnt_fs ? true : false;
```suggestion
    return mnt_fs != nullptr;
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    getTabEntry();
IMO this is an antipattern. Instead of having to call a method manually to have a member available, calling the method should be the primary way to get to that member, i.e.:

```
if (getTabEntry() == nullptr)
    throw ...
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    return std::string(opt).substr(0, len);
```suggestion
    return std::string(opt, len);
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    int rc = mnt_fs_get_option(mnt_fs, option.c_str(), &opt, &len);
What does this return if the option is set, but without a value? Probably an empty string.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +        throw std::range_error{"Option " + option + " not found for file system " + target + "."};
Is it really exceptional if an option is not set?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +std::string Mount::getOption(std::string option) {
Misleading name, this returns the value of the option

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    char* new_opts = strdup(current_opts);
Why not `std::string new_opts = current_opts;`?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    std::filesystem::create_directories(mounttarget);
Should IMO be done by the caller

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    struct libmnt_table* snap_table = mnt_new_table();
"snap" doesn't have a meaning here

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +        if ((rc = mnt_fs_set_source(mnt_fs, target.c_str())) != 0) {
This sets the source to the target - not really a general purpose bind mount anymore.
It also does this only if `mnt_fs` wasn't initialized yet.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.h
> +#include <libmount/libmount.h>
Can be avoided by forward declarations

2020-07-13 13:51 UTC, Vogtinator commented on lib/Snapshot.h
> +    std::string getUid() { return snapshotId; };
Not a user id?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Snapshot/Snapper.cpp
> +    std::string boolstr = "true";
```suggestion
    std::string boolstr = readonly ? "true" : "false";
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Snapshot/Snapper.cpp
> +    if (desc.find("transactional-update-in-progress=yes") == std::string::npos)
Case of https://i.redd.it/3c86gua5n9201.jpg

2020-07-13 13:51 UTC, Vogtinator commented on lib/Snapshot/Snapper.cpp
> +    if (ro == "ro=true")
```
    return ro == "ro=true";
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Snapshot/Snapper.cpp
> +        return Util::exec("snapper --no-dbus " + opts);
Save that dbus didn't work last time and not try again later?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Supplement.h
> +namespace fs = std::filesystem;
Maybe `using Path = std::filesystem::path;` in `Supplements`?

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +            remove(config.get("LOCKFILE").c_str());
Dead code

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +        int status = lockf(lockfile, F_TLOCK, (off_t)10000);
Why `10000`?

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +        lockfile = open(config.get("LOCKFILE").c_str(), O_CREAT|O_WRONLY);
`O_CREAT` needs a third argument, this here is undefined behaviour.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +public:
Needs deletion of copy construction and assignment.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +        throw ret;
Using exceptions for control flow, ugh. Just make it a normal method and let it return `int`?

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.h
> +    virtual ~Transkit() = default;
Why even have a destructor?

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.h
> +#ifndef TRANSACTIONALUPDATE_H_
Wrong name

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +            throw runtime_error{"Could not create lock file '" + config.get("LOCKFILE") + "': " + strerror(errno)};
If the constructor throws, the destructor is still called, but at this point `lockfile` is negative and closing will fail.
Not sure what happens with `remove`, but probably nothing good either.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +    cout << "transkit @VERSION@ started" << endl;
No inline replacement please, there are header generators for automake, cmake and meson available.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +int Transkit::parseOptions(int argc, const char *argv[]) {
Doesn't actually just parse options.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +            throw runtime_error{"Chrooting to " + bindDir + " failed: " + string(strerror(errno))};
This throws in the child process, which proceeds to unwind the stack and exits. This means all objects are destructed, files closed, stuff unmounted, etc. while the parent is still doing the `waitipid` below.

You must only use `_exit(1)` here.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +        ret = waitpid(pid, &status, 0);
Have to loop until `WIFSIGNALED(status) || WIFEXITED(status)`. Maybe also handle `EINTR`.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +    return WEXITSTATUS(status);
Belongs in the final `else`

2020-07-13 13:51 UTC, Vogtinator commented on lib/Supplement.cpp
> +void Supplements::addLink(fs::path source, fs::path target) {
Naming here is confusing. What will be the link and what does it point to?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +    for (auto it = dirsToMount.begin(); it != dirsToMount.end(); ++it) {
```
for(auto dir : dirsToMount)
    dir->mount(snapshot->getRoot());
```

2020-07-13 13:51 UTC, Vogtinator commented on lib/Mount.cpp
> +    if ((rc = mnt_fs_set_target(mnt_fs, mounttarget.c_str())) != 0) {
If you `mount("/foo")` and then `persist("/etc/fstab")`, does this overwrite the target?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Util.cpp
> +            std::not1(std::ptr_fun<int, int>(std::isspace))));
Lambdas are the way to go here

2020-07-13 13:51 UTC, Vogtinator commented on lib/Util.cpp
> +    auto pipe = popen(cmd.c_str(), "r");
`popen` is simpler, but means that shell expansion is done, which can be annoying. This also doesn't capture `stderr`.

2020-07-13 13:51 UTC, Vogtinator commented on lib/Util.cpp
> +        throw ExecutionException{"`" + cmd + "` returned with error code " + to_string(rc%255) + ".", rc};
Why `rc%255`?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +    // When all mounts are set up, then bind mount everything into a temporary
Can this be optimized away by just doing `mount --bind /foo /foo` before?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +            if (BindMount{path.path()}.isMount())
This essentially does everything in `BindMount` twice

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +    dirsToMount.push_back(make_unique<PropagatedBindMount>("/proc"));
Should be next to `/dev`?

2020-07-13 13:51 UTC, Vogtinator commented on lib/Transaction.cpp
> +    if (mntVar.isMount()) {
AFAIK, this is to detect the old layout of having `/var` as part of the snapshot, but the directories below as subvolumes.
Wouldn't it need to bind mount those in any case?

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +    cout << "Syntax: transkit [option...] command" << endl;
`endl` is for flushing, for newlines `\n` shold be used.
In this case I recommend a raw string literal.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +void Transkit::getHelp() {
If a cat it stuck in a tree and someone calls `getHelp()` no help will arrive. Why? Because the name is wrong, it only prints it.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +#include "../lib/Configuration.h"
Do not use `../` in includes, prefer passing proper include paths to the compiler.

2020-07-13 13:51 UTC, Vogtinator commented on transkit/transkit.cpp
> +            waitForSnapNum = true;
Why `waitForSnapNum` and not just getting the next argument?

2020-07-13 13:55 UTC, Vogtinator commented
UUIDs are standardized: https://en.wikipedia.org/wiki/Universally_unique_identifier This uses plain numbers instead of UUIDs.

2020-07-13 13:56 UTC, Vogtinator commented on transkit/transkit.cpp
> +    cout << "\tCreates a new transaction and prints its UUID" << endl;
UUIDs are standardized: https://en.wikipedia.org/wiki/Universally_unique_identifier This uses plain numbers instead of UUIDs.

2020-07-13 13:56 UTC, Vogtinator commented on lib/Mount.cpp
> +        tulog.error("Error reading mtab for umount");
Logging errors and throwing exceptions is done inconsistently. Sometimes errors are logged and it continues as normal, most likely leading to a crash.

2020-07-13 13:57 UTC, Vogtinator commented on lib/Mount.cpp
> +    if ((rc = mnt_context_set_fs(mnt_cxt, mnt_fs)) != 0) {
Bracing style is inconsistent.

2020-07-13 13:58 UTC, Vogtinator commented on transkit/transkit.cpp
> +    cout << "execute <command>" << endl;
How does it behave if more than one transaction/snapshot is open? Like with `transactional-update.timer` running while salt is busy doing stuff as well.

2020-07-14 14:37 UTC, Vogtinator requested changes
Next batch of comments

2020-07-14 14:37 UTC, Vogtinator commented on lib/Transaction.h
> +  the "TransactionalCommand" base class; that way it is made sure that all
Not the case (anymore?)

2020-07-14 14:37 UTC, Vogtinator commented on lib/Transaction.h
> +/*
It seems like this is the only class which is meant for direct public consumption.
Everything in public header files has to stay pretty much the same (adding non-virtual methods is allowed) to not break ABI. Unless this library is meant to bump its SOVERSION incompatibly with basically every change (like libzypp), it's a good idea to separate private from public classes and make use of https://en.cppreference.com/w/cpp/language/pimpl.

2020-07-14 14:37 UTC, Vogtinator commented on lib/Configuration.cpp
> +    econf_err error = econf_newIniFile(&key_file);
Doesn't actually read from a file - is that intentional?

2020-07-14 14:37 UTC, Vogtinator commented on lib/Configuration.cpp
> +        {"DRACUT_SYSROOT", "/sysroot"},
Does it make sense to have that configurable?

2020-07-14 14:37 UTC, Vogtinator commented on lib/Configuration.cpp
> +        {"LOCKFILE", "/var/run/transactional-update.pid"},
IMO also not useful to configure this

2020-07-14 14:37 UTC, Vogtinator commented on lib/Configuration.cpp
> +        {"OVERLAY_DIR", "/var/lib/overlay"}
In some places overlay is about `/etc` only while in other places like here it's treated more generically though there's only one user currently.

2020-07-14 14:37 UTC, Vogtinator commented on lib/Configuration.cpp
> +        error = econf_setStringValue(key_file, "", e.first, e.second);
Can libeconf actually work with an empty group here? Note also that `""` != `"[]"`

2020-07-14 14:37 UTC, Vogtinator commented on lib/Util.h
> +struct CString {
Only used once - so just calling free manually should be fine.
If not, should delete copy and assignment operators and be renamed to something else as it's actually a container or pointer

2020-07-14 14:37 UTC, Vogtinator commented on lib/Util.h
> +struct Util {
That's what namespaces are for

2020-07-14 14:37 UTC, Vogtinator commented on lib/Util.cpp
> +void Util::stub(string option) {
Unused, should be removed. If not, should throw an exception instead to inform the callers.

2020-07-14 14:37 UTC, Vogtinator commented on lib/Util.cpp
> +// trim from both ends (in place)
Only place where `ltrim` is used and `rtrim` can be replaced by a full `trim` as well. So I'd just combine those.

Could also make use of `std::string_view`, but that's more complex to handle as it's only borrowed.

2020-07-14 14:37 UTC, Vogtinator commented on lib/Transaction.cpp
> +    return snapshot ? true : false;
Better be really sure:

```
    return !!bool(((snapshot == true) != false) ? bool(true) : bool(false));
```

2020-07-14 14:37 UTC, Vogtinator commented on lib/Transaction.cpp
> +string Transaction::getSnapshot()
Misleading name, returns the ID

2020-07-14 14:37 UTC, Vogtinator commented on lib/Supplement.h
> +    void cleanup();
A cleanup method but no destructor?

2020-07-14 14:37 UTC, Vogtinator commented on lib/Supplement.h
> +    Supplements() = default;
A default-constructed `Supplements` object doesn't really make sense. Maybe use `std::optional` instead.

2020-07-14 14:37 UTC, Vogtinator commented on lib/Overlay.cpp
> +    } catch (exception e) {}
What's actually expected here? It has to print a warning at least.

2020-07-14 14:37 UTC, Vogtinator commented on lib/Overlay.cpp
> +        while (getline(ss, lowerdir, ':')) {
ADL, ew.

2020-08-07 07:27 UTC, laenion commented on lib/Configuration.h
> +#include <libeconf.h>
Good point - will be changed.

2020-08-07 09:10 UTC, laenion commented on lib/Configuration.cpp
> +/*
Yes; applied for the new C++ files.

2020-08-07 09:16 UTC, laenion commented on lib/Configuration.cpp
> +    for(auto &e : defaults) {
Good idea - the source is using C++17 anyway, so let's also modernize this.

2020-08-07 12:12 UTC, laenion commented on lib/Configuration.h
> +inline Configuration config{};
The point of using the inline variable is to provide a config object that is "just there", without having to worry about a place to initialize it.
I agree that it may not be the nicest thing to do IO during static initialization, but the ease of use definitely outweighs this for me.

2020-08-07 12:15 UTC, laenion commented on lib/Configuration.h
> +    std::string get(const std::string &key);
Fixed.

2020-08-07 12:17 UTC, laenion commented on lib/Configuration.h
> +#ifndef CONFIGURATION_H_
... is non-standard, and the IDE added the include guard automatically, so let's keep using them.

2020-08-13 15:05 UTC, laenion commented on lib/Exceptions.h
> +    const char* what() const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override {
Because I'm stupid and used the wrong function signature...

2020-08-13 15:27 UTC, laenion commented on lib/Exceptions.h
> +    int getReturnCode() {
Usually it's preferred to use getter / setter methods, just in case one wants to add additional checks later. Moreover in this specific case the only other class value is also retrieved via method call, so it would be inconsistent to use both ways.

The class is indeed missing a few `const`s, though.

2020-08-19 13:39 UTC, Vogtinator commented on lib/Configuration.h
> +inline Configuration config{};
I don't see how the singleton pattern is any harder to use.

2020-08-19 13:50 UTC, Vogtinator commented on lib/Configuration.h
> +#ifndef CONFIGURATION_H_
I'm very much against the use of #include guards in this century.

https://en.wikipedia.org/wiki/Pragma_once#Portability

And it also improves compilation speed.

2020-08-19 13:51 UTC, Vogtinator commented on lib/Exceptions.h
> +    int getReturnCode() {
> Usually it's preferred to use getter / setter methods, just in case one wants to add additional checks later.

Then those getter setters can be added later as well - let's write a program for the present, we don't know the demands of the future anyway.

2020-08-24 09:19 UTC, laenion commented on lib/Exceptions.h
> +    ExecutionException(std::string why, int status) : reason{why}, returncode{status} {
Agreed, and status could also need a const declaration. Fixed.

2020-08-24 09:21 UTC, laenion commented on lib/Exceptions.h
> +    ExecutionException(std::string why, int status) : reason{why}, returncode{status} {
Yes, the naming indeed seems a little inconsistent. Changed to matching names.

2020-08-24 09:32 UTC, laenion commented on lib/Log.h
> +        time_t now = time(0);
You are talking about adding the `std` namespace here?

2020-08-24 09:37 UTC, Vogtinator commented on lib/Log.h
> +        time_t now = time(0);
Yes. Currently it's mixing things up.

2020-08-25 17:17 UTC, laenion commented on lib/Log.h
> +        time_t now = time(0);
Consistently using `std::` namespace now.

2020-08-25 17:18 UTC, laenion commented on lib/Log.h
> +        if (int(level) >= int(TULogLevel::ERROR))
It seems this was a leftover from a previous implementation - thanks for noticing!

2020-08-25 17:19 UTC, laenion commented on lib/Mount.h
> +#ifndef LIBMOUNTWRAPPER_H
Fixed.

2020-08-26 15:31 UTC, laenion commented on lib/Configuration.h
> +#ifndef CONFIGURATION_H_
All other projects I have checked for reference are also using include guards, so let's keep to the well established standards. I've unified the names and added prefixes to not conflict with potential includes form other libraries though.

2020-09-15 11:26 UTC, Conan-Kudo commented
@laenion Can you please make the C++ library LGPLv2+? That aligns it well with the libdnf library license.

2020-10-12 13:44 UTC, Conan-Kudo requested changes

2020-10-12 13:44 UTC, Conan-Kudo commented on transkit/transkit.h
> +/* SPDX-License-Identifier: GPL-2.0-only */
Why `GPL-2.0-only`? Why not `GPL-2.0-or-later`?

2020-10-12 13:45 UTC, laenion commented on transkit/transkit.h
> +/* SPDX-License-Identifier: GPL-2.0-only */
> @laenion Can you please make the C++ library LGPLv2+? That aligns it well with the libdnf library license.

Done, see commit 712db9ba2fab7b1978ff3b8810705ca4db5f3382.

2020-10-12 13:52 UTC, laenion commented on transkit/transkit.h
> +/* SPDX-License-Identifier: GPL-2.0-only */
> Why `GPL-2.0-only`? Why not `GPL-2.0-or-later`? The current application is GPLv2+ already...

Hmmm... Indeed, it seems I just had a look at the license file itself, not the headers when checking the previous license. Thanks for the notice, will fix.

2020-10-22 14:30 UTC, laenion commented on lib/Transaction.cpp
> +    if (mntVar.isMount()) {
No, because on old layouts with separate subvolumes below _/var_ the mentioned directories are part of the root file system snapshot and thus available unconditionally.

2020-10-22 14:40 UTC, laenion commented on transkit/transkit.cpp
> +    cout << "Syntax: transkit [option...] command" << endl;
Agreed.

2020-10-22 14:51 UTC, laenion commented on transkit/transkit.cpp
> +void Transkit::getHelp() {
The cat then ran to the developer and complained. [But now the cat is escaped](http://geek-and-poke.com/geekandpoke/2010/2/20/the-geek-joke-of-the-week.html) (see above).

2020-10-22 14:54 UTC, laenion commented on transkit/transkit.cpp
> +            waitForSnapNum = true;
Because `--continue` can be called both with and without an argument. If the argument is missing it will just resume the current default snapshot; as no snapshot number is following in that case the next option has to be processed.

2020-10-22 14:57 UTC, laenion commented on transkit/transkit.cpp
> +    cout << "\tCreates a new transaction and prints its UUID" << endl;
To be exact it uses whatever the underlying snapshot management tool is using. In the case of zypper that's a number, but for example with ZFS it would be a real UUID.

2020-10-22 15:02 UTC, laenion commented on transkit/transkit.cpp
> +    cout << "\tCreates a new transaction and prints its UUID" << endl;
Replaced with "unique ID / ID".

2020-10-22 15:36 UTC, laenion commented on transkit/transkit.cpp
> +    cout << "execute <command>" << endl;
Your example mentions **running** two transkit instances at the same time. That's not possible, there's a locking mechanism in place to prevent such cases: https://github.com/openSUSE/transactional-update/blob/f24b596602612840fd18d2e1461fdec12f7dbc14/transkit/transkit.cpp#L130-L152

However the way it is currently implemented multiple snapshots can be **open** at the same time. This is to prevent blocking an application from opening a new snapshot if a previous one was left open (e.g. when the application opening it crashed or if the user forgot to close the snapshot after opening). I'm not sure if there's a use case for modifying multiple snapshots independently apart from that.

2020-10-22 16:06 UTC, laenion commented on lib/Configuration.cpp
> +    econf_err error = econf_newIniFile(&key_file);
For now it is, yes, because I'm not entirely sure yet which components will share the same configuration files.

2020-10-22 16:09 UTC, laenion commented on lib/Configuration.cpp
> +        {"DRACUT_SYSROOT", "/sysroot"},
I'll need to define it somewhere anyway. The configuration framework provides a convenient way to set those variables.

2020-10-22 16:09 UTC, laenion commented on lib/Configuration.cpp
> +        {"LOCKFILE", "/var/run/transactional-update.pid"},
Same here.

2020-10-27 07:57 UTC, laenion commented on lib/Mount.cpp
> +    if ((rc = mnt_table_parse_mtab(umount_table, NULL)) != 0)
Optimized.

2020-10-27 08:02 UTC, laenion commented on lib/Mount.cpp
> +    : mnt_cxt{NULL}, mnt_table{mnt_new_table()}, mnt_fs{NULL},
Changed.

2020-10-27 08:08 UTC, laenion commented on lib/Mount.cpp
> +    : mnt_cxt{NULL}, mnt_table{NULL}, mnt_fs{NULL}
Done.

2020-10-27 08:23 UTC, laenion commented on lib/Mount.cpp
> +    struct libmnt_fs *umount_fs;
Changed.

2020-10-27 08:24 UTC, laenion commented on lib/Mount.cpp
> +    int rc;
Also noticed that during refactoring. Fixed.

2020-10-27 08:26 UTC, laenion commented on lib/Mount.cpp
> +        if ((rc = mnt_table_parse_fstab(mnt_table, NULL)) != 0)
I also thought about using this pattern, but as I'm using `rc` several times I decided to just declare it just once.

2020-10-27 08:45 UTC, laenion commented on lib/Mount.cpp
> +    tabsource = source;
Yes, `setTabSource` is not supposed to be called after `mnt_fs` has been initalized. I've prevented that explicitly now.

2020-10-27 10:46 UTC, laenion commented on lib/Mount.cpp
> +    getTabEntry();
Agreed. Changed this and the other methods to return the `libmnt_fs` struct (and reworked the functions a bit).

2020-10-27 12:27 UTC, laenion commented on lib/Mount.cpp
> +    int rc = mnt_fs_get_option(mnt_fs, option.c_str(), &opt, &len);
No, it's returning `NULL` (https://cdn.kernel.org/pub/linux/utils/util-linux/v2.36/libmount-docs/libmount-Filesystem.html#mnt-fs-get-option). However that's a good point: As C++ doesn't allow a `nullptr` assigned to a `string` anyway I'll map the `NULL` return value to an empty string.

2020-10-27 12:32 UTC, laenion commented on lib/Mount.cpp
> +        throw std::range_error{"Option " + option + " not found for file system " + target + "."};
In the context of transactional-update I'd say _Yes_: This is not a general purpose C++ Mount class. When querying something and it's not there it's an error in all cases I had so far.

2020-10-27 12:40 UTC, laenion commented on lib/Mount.cpp
> +std::string Mount::getOption(std::string option) {
So when we are getting the value of the option, why is `getOption()` a misleading name?

2020-10-27 12:47 UTC, laenion commented on lib/Mount.cpp
> +    char* new_opts = strdup(current_opts);
Because when converting the C++ string back to a C string (required by the following functions) I'd get a `const char*`, while the functions require `char**` to be able to write the value back.

2020-10-27 12:53 UTC, laenion commented on lib/Mount.cpp
> +    std::filesystem::create_directories(mounttarget);
In the context of transactional-update I think it's more convenient to do that as part of the mount command itself: Especially with bind mounts it's not guaranteed that the mount point exists on the root file system, and we have a lot of directories to mount - so I don't think it's helpful having to create each of them in a separate step.

2020-10-27 12:58 UTC, laenion commented on lib/Mount.cpp
> +    struct libmnt_table* snap_table = mnt_new_table();
It does: It is the fstab file of the _snapshot_ - all the other operations are using the tables from the running system.

2020-10-28 15:20 UTC, laenion commented on lib/Mount.cpp
> +        if ((rc = mnt_fs_set_source(mnt_fs, target.c_str())) != 0) {
> This sets the source to the target - not really a general purpose bind mount anymore.

What is a "general purpose bind mount"? The class is initialized with a specific target already...
For most mounts the _target_ directory of the running system and the chroot environment is identical (i.e. the target `/root` will mount the running system's `/root` into the chroot's `/root`. As it represents both the _source_ and the _target_ (in the default case) I renamed it to _mountpoint_ to maybe make this more clear. Additionally the code was duplicated code anyway. I replaced it with a call to `setSource()`.

> It also does this only if `mnt_fs` wasn't initialized yet.

This is to enable the default behaviour from above; if users specify a source themselves, then it won't be reset here.

2020-10-30 14:18 UTC, laenion commented on transkit/transkit.cpp
> +int Transkit::parseOptions(int argc, const char *argv[]) {
Agreed - split into option parsing and command execution now. Migrated to using `getopt` while at it.

2020-10-30 14:26 UTC, Conan-Kudo commented
@laenion Have you considered using popt for this? That way the usage stuff can even be translated...

2020-10-30 14:28 UTC, laenion commented on transkit/transkit.cpp
> +            waitForSnapNum = true;
Now that the options are parsed by `getopt` this is made unambiguous, but the option syntax changed slightly (i.e. it's now `-c<num>` or `--continue=<num>` instead of `-c <num>` / `--continue <num>` (with spaces).

2020-10-30 14:57 UTC, laenion commented
No - I had a look at _Boost.Program_options_, but that one doesn't support stopping to process the arguments on the first non-option argument (e.g. in `transkit execute ls -l` the `-l` would always be taken as an option of `transkit` instead of `ls`). From what I can see _popt_ doesn't support that either, and additionally it doesn't even know about optional arguments...

2020-11-09 12:54 UTC, Vogtinator commented on transkit/transkit.cpp
> +            waitForSnapNum = true;
Much better!

2020-11-09 13:37 UTC, Vogtinator commented on lib/Mount.cpp
> +        throw std::range_error{"Option " + option + " not found for file system " + target + "."};
Instead of throwing an exception here, this could use `std::optional` and return `std::nullopt` in that case.

2020-11-09 13:38 UTC, Vogtinator commented on lib/Mount.cpp
> +std::string Mount::getOption(std::string option) {
Because it returns the value of the option. If you have something like `foo=42,bar`, `getOption("bar") == ""`...

2020-11-09 13:43 UTC, Vogtinator commented on lib/Mount.cpp
> +    char* new_opts = strdup(current_opts);
Use cleanup attributes or a proper c++ RAII holder

2020-11-09 13:44 UTC, Vogtinator commented on lib/Mount.cpp
> +    struct libmnt_table* snap_table = mnt_new_table();
What I mean is that this function is not in any way specific to snapshots - it's just called `persist` after all. It works for all fstabs, not just in snapshots.

2020-12-09 17:51 UTC, laenion commented on transkit/transkit.cpp
> +#include "../lib/Configuration.h"
Done

2020-12-10 01:16 UTC, Conan-Kudo requested changes

2020-12-10 01:16 UTC, Conan-Kudo commented on t-u.pc.in
> +Name: transactional-update
Please call it `tukit` instead of `transactional-update`, and rename the file accordingly. This is about the _library_, so think of it that way rather than from the program.

2020-12-10 01:16 UTC, Conan-Kudo commented on t-u.pc.in
> +Libs: -L${libdir} -lt-u
This should be `${includedir}/tukit` and `-ltukit` instead.

Also, something to consider here: perhaps making everyone have to do `#include <tukit/Transaction.h>` isn't a bad idea. I'm already assuming that for my plugin code.

2020-12-10 08:48 UTC, laenion commented on t-u.pc.in
> +Name: transactional-update
The *library* itself is called `TransactionalUpdate` (or `libt-u` for short), the command line helper application using that library is called `tukit`.

2020-12-10 09:00 UTC, Conan-Kudo commented on t-u.pc.in
> +Name: transactional-update
Hmm, I see. Then you should probably rename this pkgconfig file to `transactional-update.pc.in` since that's the name you're going with.

2020-12-10 09:11 UTC, laenion commented on t-u.pc.in
> +Name: transactional-update
The name of the `.pc` file has to match the library file name, `libt-u.so` in this case. On the other hand `libtransactional-update.so` seemed overly long, so I used the short form...

2020-12-10 09:13 UTC, Conan-Kudo commented on t-u.pc.in
> +Name: transactional-update
I hope nobody is typing the library name out anyway...

2020-12-11 11:20 UTC, merged

2020-12-11 11:23 UTC, laenion commented
Merging the current state into master due to popular demand - the remaining review comments will be handled there. The public header file also got some documentation.