Implement setup-selinux option
openSUSE/transactional-update pull request #39
Opened 2020-08-20 13:16 UTC by thkukuk

This option installs and enables the targeted SELinux policy.
The required steps are:
 1. Make sure the policies are installed
 2. Adjust /etc/default/grub
 3. Adjust /etc/selinux/config
 4. Rebuild grub.cfg and initrd

2020-09-29 16:56 UTC, Conan-Kudo approved these changes

2020-09-29 16:56 UTC, Conan-Kudo commented on sbin/transactional-update.in
> +    test -d /var/lib/selinux || mkdir -p /var/lib/selinux
Shouldn't this be handled by the `selinux-policy` package?

2020-09-29 16:57 UTC, Conan-Kudo requested changes

2020-09-29 16:57 UTC, Conan-Kudo commented on sbin/transactional-update.in
> +    test -d /var/lib/selinux || mkdir -p /var/lib/selinux
Shouldn't this be handled by the `selinux-policy` package?

2020-09-29 17:16 UTC, thkukuk commented on sbin/transactional-update.in
> +    test -d /var/lib/selinux || mkdir -p /var/lib/selinux
The selinux-policy package has the design mistake to install files in /var. So we need to make sure they are visible outside the snapshot. And thus we need to create this directory before we can install the package, after installing the package is too late.
This is only the selinux code for a fresh installation, not for a selinux update. That's why you don't see in the patch the usage of this directory before the package gets installed, it's already since a longer time there.

2020-09-29 17:17 UTC, Conan-Kudo commented on sbin/transactional-update.in
> +    test -d /var/lib/selinux || mkdir -p /var/lib/selinux
I see. Makes sense 👍

2020-09-29 17:17 UTC, Conan-Kudo approved these changes

2020-09-29 17:18 UTC, Conan-Kudo commented
@thkukuk Do we already set it up by default in new MicroOS instances (that is, have the packages there, just have the policy setting set to permissive or something)?

2020-09-29 17:24 UTC, thkukuk commented
@Conan-Kudo At first we need SELinux 3.1 in Factory, this is blocked by the required glibc update. Then we need the policy back in Factory, this is blocked by SELinux 3.1.
Then @laenion needs to finally accept this pull request ...
My MicroOS instances are running with SELinux enabled since weeks, only getting this into Factory is more complicated then it should be ...
And finally we need to cleanup our SELinux packages much more and bring them in sync with "upstream".

2020-09-29 17:25 UTC, Conan-Kudo commented
Yeah, that makes sense to me.

2020-10-22 07:34 UTC, laenion commented
To be honest I'm not really happy to put this into transactional-update, but putting this in a helper script revealed different problems like unlabeled intermediary snapshots. I'm thus (finally) merging this change as transactional-update requires dedicated SELinux support anyway.

2020-10-22 07:35 UTC, merged