Merge /etc before dropping the snapshot
openSUSE/transactional-update pull request #40
Opened 2020-09-07 18:15 UTC by aplanas

2020-09-07 19:06 UTC, aplanas commented
Do not merge yet, some trivial changes in /etc generate invalid data: `transactional-update --drop-if-no-change run touch /etc/test` is generating broken files in my setup

2020-09-07 19:19 UTC, thkukuk commented
On Mon, Sep 07, Alberto Planas wrote:

>   • Mount /run in the chroot

That's a really bad idea, as this can have a high impact on the
running system, thus the update is no longer atomic.

2020-09-07 19:27 UTC, aplanas commented
Drop `Mount /run in the chroot`. If /run is mounted, will be only under the `run` sub-command and not in the general case.

2020-09-08 14:05 UTC, laenion requested changes

2020-09-08 14:05 UTC, laenion commented on sbin/transactional-update.in
> +    # If needed, merge the orverlay from the snapshot to the current /etc
Typo: "orverlay"
But imho the comment isn't very self-explanatory anyway. Better write something like "Even if the snapshot itself did not contain any changes, /etc may do so. Changes in /etc may be applied immediately, so merge them back into the running system."

2020-09-08 14:05 UTC, laenion commented on sbin/transactional-update.in
> +ETC_OVERLAY_DIR_PREV=""
This variable isn't used anywhere.

2020-09-08 14:05 UTC, laenion commented on sbin/transactional-update.in
> +	rsync --archive --inplace --xattrs --filter='-x security.selinux' --acls --exclude 'fstab' --delete --quiet "${SNAPSHOT_DIR}/etc/" /etc
Why don't you move this block up into the rollback section 3 lines above? I don't see any immediate reason to use an additional variable / separate step for this...

2020-09-08 14:09 UTC, aplanas commented on sbin/transactional-update.in
> +ETC_OVERLAY_DIR_PREV=""
https://github.com/openSUSE/transactional-update/blob/master/sbin/transactional-update.in#L990 uses it. Do you want me to remove it?

2020-09-08 14:10 UTC, aplanas commented on sbin/transactional-update.in
> +    # If needed, merge the orverlay from the snapshot to the current /etc
Yes, done.

2020-09-08 14:11 UTC, aplanas commented on sbin/transactional-update.in
> +	rsync --archive --inplace --xattrs --filter='-x security.selinux' --acls --exclude 'fstab' --delete --quiet "${SNAPSHOT_DIR}/etc/" /etc
Indeed.

2020-09-09 06:32 UTC, laenion commented
This change is necessary for Salt integration as discussed in https://etherpad.suse.de/p/salt-microos.

2020-09-09 06:33 UTC, merged