Add documentation for tukit.conf (bsc#1192307)
openSUSE/transactional-update pull request #76
Opened 2021-11-03 15:27 UTC by aplanas

2021-11-10 14:29 UTC, laenion commented
I'll merge this for transactional-update 4.0 along with a man page for `tukit` itself (which is also still undocumented yet).

Just one note: I think we *never* want to add _/var/lib_ to the list of bind mounts.
The whole concept of transactional updates is based around the concept that an update can *not* break the currently running system. By bind-mounting such a vital directory that whole concept is basically nullified - and on the contrary will cause significant side effects:

/var/lib contains a lot of data, including databases, docker images or sssd data. That data is often bound to a specific version of the software.
A simple example: Imagine that a database package is updated, and that update also includes a schema change which the post script will perform if a database is found. Now we run into the situation that the database is still running the *old* version in the currently active system and suddenly gets confronted with a changed and probably incompatible new data set belonging to the *new* version (with the new database daemon only available in the new snapshot which hasn't been booted yet). Due to the bind mount however the new data leaks into the current system. This is playing with fire.

Because of that I'm really interested to hear what the use case for adding /var/lib to the bind mounts would be.

2021-11-10 14:36 UTC, aplanas commented
> I'll merge this for transactional-update 4.0 along with a man page for `tukit` itself (which is also still undocumented yet).

Sure. Will you prepare this?

> Just one note: I think we _never_ want to add _/var/lib_ to the list of bind mounts. The whole concept of transactional updates is based around the concept that an update can _not_ break the currently running system. By bind-mounting such a vital directory that whole concept is basically nullified - and on the contrary will cause significant side effects:

Indeed.

The issue is that there are some kubernetes installers that are doing this: updating `/var/lib`, adding directories there (like `/var/lib/rancher`).  This can be view as a bug in the installer (should use something different that `/var/lib`), but sadly is required as today.

> /var/lib contains a lot of data, including databases, docker images or sssd data. That data is often bound to a specific version of the software. A simple example: Imagine that a database package is updated, and that update also includes a schema change which the post script will perform if a database is found. Now we run into the situation that the database is still running the _old_ version in the currently active system and suddenly gets confronted with a changed and probably incompatible new data set belonging to the _new_ version (with the new database daemon only available in the new snapshot which hasn't been booted yet). Due to the bind mount however the new data leaks into the current system. This is playing with fire.

I will add as a comment in the documentation.

> Because of that I'm really interested to hear what the use case for adding /var/lib to the bind mounts would be.

Rancher.

2021-11-10 14:38 UTC, laenion commented
> > Because of that I'm really interested to hear what the use case for adding /var/lib to the bind mounts would be.
> 
> Rancher.

But I guess to bind mount /var/lib/rancher would be enough then? Otherwise the whole concept of transactional-update is spoiled...

2021-11-10 14:41 UTC, aplanas commented
> > > Because of that I'm really interested to hear what the use case for adding /var/lib to the bind mounts would be.
> > 
> > 
> > Rancher.
> 
> But I guess to bind mount /var/lib/rancher would be enough then? Otherwise the whole concept of transactional-update is spoiled...

IIUC not always, as this can be created by the installer.  This should be OK if:

1) The user create first the directory.

2) There is an specific partition created during the installation, and is already in fstab

2021-11-10 14:52 UTC, aplanas commented
I changed the example, and I try to integrate the dangers of exposing /var/lib

2022-07-08 11:23 UTC, MaxiMii05 commented on man/tukit.conf.5.xml
> +	    Note that is some situations we should be tempted to
Just seeing this by chance and thought I could suggest fixing a typo and maybe a logical error (depending on how it's meant).
is -> in
should -> could

2022-07-08 11:47 UTC, aplanas commented on man/tukit.conf.5.xml
> +	    Note that is some situations we should be tempted to
I found and fixed the "is -> in", but I am not sure about the second one.

Thanks!

2022-07-14 11:37 UTC, laenion requested changes
Thanks a lot for the documentation! Generally I really like it, just a few nits inline.

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +    <para>The <refname>transactional-update.conf</refname> file uses INI
The _tukit.conf_ file.

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +             Directory where <literal>dracut</literal> will mount the
Spare space at the beginning of the line.

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +            Lock file path for tukit. By default is
By default _it_ is

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +            stored.  By default is <literal>/var/lib/overlay</literal>
Spare space after the dot, and again "By default _it_ is". And it's missing a dot at the end :-) (Same at the previous comment.)

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +	    entry with a different id between the brackets for each.
The spare spaces from above could be inserted here at the beginning of the line ;-)

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +            *not* get a seperate snapshot (so their contents cannot be
sep**a**rate

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +            system itself, i.e. any additional mounts added here will
Maybe "Be aware that only the root file system is managed in a transactional way, i.e. ..." would be clearer? Otherwise the sentence is probably missing a "to" between "done" and "the".

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +           applications in there are usually self-contained.
Missing space at beginning of line.

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +            <literal>/var/lib/images</literal>.
No "we" form in documentation please. Change that to something like

"Example: To mount additional directories such as
...
into the update environment, add the following lines to the configuration file:"

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +            in a different partition, we should list both:
No "we" form here, too. Maybe change to

"If a directory contains submounts, these have to be mounted separately. For example if for some reason <literal>/usr/local</literal> should contain <literal>/usr/local/extra</literal> that is located on a different partition, both mounts will have to be listed:"

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +	    Note that is some situations we should be tempted to
I agree on the "should" -> "could" comment: One _may_ or _could_ be tempted, but one never _should_ be tempted ;-)

Again, to avoid the "we" form I'd suggest you could write "... one may be tempted to ...".

2022-07-14 11:37 UTC, laenion commented on man/tukit.conf.5.xml
> +	  </para>
The whole paragraph has wrong spacing. (Missing 4 spaces)

2022-07-14 12:03 UTC, aplanas commented on man/tukit.conf.5.xml
> +    <para>The <refname>transactional-update.conf</refname> file uses INI
Done!

2022-07-14 12:03 UTC, aplanas commented on man/tukit.conf.5.xml
> +            Lock file path for tukit. By default is
Done

2022-07-14 12:03 UTC, aplanas commented on man/tukit.conf.5.xml
> +            stored.  By default is <literal>/var/lib/overlay</literal>
I reformatted all the `<para>`. I used a normal XML indentation here, expecting that spaces are not relevant.

2022-07-14 12:04 UTC, aplanas commented on man/tukit.conf.5.xml
> +            *not* get a seperate snapshot (so their contents cannot be
Done

2022-07-14 12:50 UTC, merged

2022-07-14 12:51 UTC, laenion commented
The 4.0 release is very near, so finally merging this PR.